name: 'retail_insights'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  retail_insights:
    01_staging:
      +database: DATA_VAULT
      +schema: STAGING
      +materialized: table

    02_raw_vault:
      +database: DATA_VAULT
      +schema: RAW_VAULT
      +materialized: incremental
      +incremental_strategy: append
      +on_schema_change: append_new_columns

    03_business_vault:
      +database: DATA_VAULT
      +schema: BUSINESS_VAULT
      +materialized: table

    04_marts:
      +database: ANALYTICS
      +schema: MARTS
      +materialized: table
